on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: pylint
    steps:
    - name: run pylint
      id: pylint
      uses: LakshitF/pylint3-action@master
      with:
        filename: 'bot.py'
